name: Deploy Hello World

on:
  push:
    branches:
      - main

permissions:
  contents: read # for checkout
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Show Python Version
        run: python3 -V

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' 
      
      - name: Run Hello World
        run: python helloworld.py
